### ISSUE TITLE
[BUG] Invalid parameter configuration provided for $configPaths argument

### ISSUE THREAD

**Issue by griest024** [graycoreio/magento2-daffodil#13]
This happened after the upgrade to Magento 2.4.3.

**Comment by damienwebdev** [comment]
@griest024 at what point in time did you get this error?

**Comment by griest024** [comment]
This happened when running a graphql query, I think the get filter types query.

**Comment by damienwebdev** [comment]
@griest024 are you still seeing this?

**Comment by griest024** [comment]
I haven't noticed this for a while, closing for now
