### ISSUE TITLE
[FEAT] Reset Password Redirect Route

### ISSUE THREAD

**Issue by griest024** [graycoreio/magento2-daffodil#19]
# :bulb: Feature request

## Feature Name

Reset Password Redirect Route

## The Desired Behavior

When Magento receives a request for the reset password route, it should redirect to an app dev-specified route on the PWA. The token set in query param needs to be passed along as well.

## Your Use Case

As an app dev, I'd like to be able to specify the PWA route which will be used as the reset password landing page.

**Comment by damienwebdev** [comment]
Handled by the configuration enabled by 32bc5c92a00cf8975560db485c454bf87963ef72 and released 0.2.1.
