### ISSUE TITLE
[FEAT] Set Query Complexity Limit

### ISSUE THREAD

**Issue by griest024** [graycoreio/magento2-daffodil#2]
# :bulb: Feature request

## Feature Name

Set Query Complexity Limit

## The Desired Behavior

I want the module to take care of setting the QC limit to an appropriate value.

## Your Use Case

A an app dev, I want the module to take of necessary config for me.

**Comment by damienwebdev** [comment]
@griest024 is this still a problem? I think generally, we've been doing a good job staying below the default in Daffodil. Does this package still need this?

**Comment by griest024** [comment]
everything seems to work just fine with the default QC limit
